# Generated by Django 4.2.16 on 2026-01-21 18:31

import django.core.validators
from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer name', max_length=100)),
                ('photo', models.ImageField(blank=True, help_text='Small square image recommended (e.g. 200x200px)', null=True, upload_to='reviews/', validators=[pages.models.validate_image_size])),
                ('review', models.TextField(help_text='Customer review (max 500 characters)', max_length=500)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
