# Generated by Django 4.2.16 on 2026-02-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteannouncement',
            name='text',
            field=models.CharField(help_text='Text shown in the top bar (e.g. Free Shipping above ₹499)', max_length=255),
        ),
    ]
