# Generated by Django 4.2.16 on 2026-02-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_siteannouncement_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteannouncement',
            name='text',
            field=models.CharField(help_text="You can use simple HTML to add colors. Example: Use Code <span style='color:#ffd700;'>SHARKTANK5</span> for <span style='color:#00cfff;'>5% OFF</span>", max_length=255),
        ),
    ]
