# Generated by Django 4.2.16 on 2026-01-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/custom/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
