# Generated by Django 4.2.16 on 2026-02-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_bulkorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='address_line_1',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='address_line_2',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='age_group',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_source',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='order_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(default='000000', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('PREPAID', 'Prepaid'), ('COD', 'Cash on Delivery')], default='COD', max_length=10),
        ),
    ]
