# Generated by Django 4.2.16 on 2026-02-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='public_order_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
