# Generated by Django 4.2.16 on 2026-02-06 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_public_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='age_group',
        ),
    ]
