# Generated by Django 4.2.16 on 2026-01-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_heroslide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroSlide',
        ),
    ]
