# Generated by Django 4.2.16 on 2026-01-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='requires_custom_image',
            field=models.BooleanField(default=False),
        ),
    ]
