# Generated by Django 4.2.16 on 2026-01-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_requires_custom_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Image shown on homepage & category cards', null=True, upload_to='categories/'),
        ),
    ]
