# Generated by Django 4.2.16 on 2026-02-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_customerreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreview',
            name='photo',
        ),
    ]
