# Generated by Django 4.2.16 on 2026-02-09 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_customerreview_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_single', to='products.product')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
