# Generated by Django 4.2.16 on 2026-02-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_hotsingle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotsingle',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='hotsingle',
            name='position',
        ),
    ]
