# Generated by Django 4.2.16 on 2026-02-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_hotsingle_options_remove_hotsingle_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_units',
            field=models.PositiveIntegerField(default=0, help_text='Total units sold'),
        ),
    ]
