# Generated by Django 4.2.16 on 2026-02-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productvideo_delete_productmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvideo',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (lower = first)'),
        ),
    ]
