# Generated by Django 4.2.16 on 2026-02-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productvideo_caption_alter_productvideo_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvideo',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='productvideo',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='productvideo',
            name='order',
        ),
    ]
