# Generated by Django 4.2.16 on 2026-04-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_has_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreview',
            name='is_video',
            field=models.BooleanField(default=False, help_text='Auto-detected: whether media is video'),
        ),
        migrations.AddField(
            model_name='customerreview',
            name='media',
            field=models.FileField(blank=True, help_text='Upload image or video', null=True, upload_to='reviews/'),
        ),
    ]
