# Generated by Django 4.2.16 on 2026-05-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_customerreview_is_video_customerreview_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gift_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
