# Generated by Django 4.2.16 on 2026-05-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_gift_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_gift_option',
            field=models.BooleanField(default=False),
        ),
    ]
